import { PlantSpeciesDef } from "../domain/types";

export const PLANT_SPECIES_DEFS: PlantSpeciesDef[] = [
  {
    id: "plant_tulip",
    nameKo: "튤립",
    rarity: "common",
    growSeconds: 120,
    rewardCoins: 30,
    stages: 4,
    seedPrice: 18,
    descriptionKo: "도톰한 꽃잎으로 색감이 또렷한 봄 대표종.",
    originKo: "중앙아시아 · 터키",
    flowerLanguageKo: "사랑의 고백",
    seasonKo: "봄",
    stemColorHex: "#4d8a52",
    bloomColorHex: "#ff6688"
  },
  {
    id: "plant_rose",
    nameKo: "장미",
    rarity: "rare",
    growSeconds: 150,
    rewardCoins: 36,
    stages: 4,
    seedPrice: 22,
    descriptionKo: "겹겹의 꽃잎으로 화려한 분위기를 만드는 대표 꽃.",
    originKo: "서아시아 · 유럽",
    flowerLanguageKo: "사랑, 열정",
    seasonKo: "봄~가을",
    stemColorHex: "#4a7f47",
    bloomColorHex: "#d7343f"
  },
  {
    id: "plant_daisy",
    nameKo: "데이지",
    rarity: "common",
    growSeconds: 90,
    rewardCoins: 24,
    stages: 4,
    seedPrice: 15,
    descriptionKo: "밝은 아침 정원을 상징하는 기본 꽃.",
    originKo: "유럽 · 서아시아",
    flowerLanguageKo: "순수, 평화",
    seasonKo: "봄~가을",
    stemColorHex: "#5f8c42",
    bloomColorHex: "#fff4a8"
  },
  {
    id: "plant_anemone",
    nameKo: "아네모네",
    rarity: "common",
    growSeconds: 110,
    rewardCoins: 28,
    stages: 4,
    seedPrice: 17,
    descriptionKo: "바람결처럼 가볍게 흔들리는 꽃잎이 매력적인 봄꽃.",
    originKo: "지중해 연안",
    flowerLanguageKo: "진실한 마음",
    seasonKo: "봄",
    stemColorHex: "#4f844f",
    bloomColorHex: "#8e75c5"
  },
  {
    id: "plant_calendula",
    nameKo: "금잔화",
    rarity: "common",
    growSeconds: 100,
    rewardCoins: 26,
    stages: 4,
    seedPrice: 16,
    descriptionKo: "따뜻한 주황빛이 정원 분위기를 밝게 바꿔주는 꽃.",
    originKo: "남유럽",
    flowerLanguageKo: "건강, 희망",
    seasonKo: "봄~초여름",
    stemColorHex: "#5b8b47",
    bloomColorHex: "#ff9a4d"
  },
  {
    id: "plant_camellia",
    nameKo: "동백꽃",
    rarity: "rare",
    growSeconds: 170,
    rewardCoins: 40,
    stages: 4,
    seedPrice: 26,
    descriptionKo: "두툼하고 윤기 있는 꽃잎이 고급스러운 분위기를 준다.",
    originKo: "동아시아",
    flowerLanguageKo: "그대를 사랑합니다",
    seasonKo: "겨울~봄",
    stemColorHex: "#3f7643",
    bloomColorHex: "#de4557"
  },
  {
    id: "plant_canna_lily",
    nameKo: "칸나",
    rarity: "rare",
    growSeconds: 180,
    rewardCoins: 42,
    stages: 4,
    seedPrice: 28,
    descriptionKo: "시원하게 뻗는 잎과 강한 색감이 돋보이는 여름꽃.",
    originKo: "열대 아메리카",
    flowerLanguageKo: "열정, 자신감",
    seasonKo: "여름",
    stemColorHex: "#437b46",
    bloomColorHex: "#f0c83e"
  },
  {
    id: "plant_carnation",
    nameKo: "카네이션",
    rarity: "rare",
    growSeconds: 160,
    rewardCoins: 38,
    stages: 4,
    seedPrice: 24,
    descriptionKo: "풍성한 주름 꽃잎이 부드러운 볼륨감을 만들어준다.",
    originKo: "지중해 연안",
    flowerLanguageKo: "감사, 존경",
    seasonKo: "봄~초여름",
    stemColorHex: "#4a7f45",
    bloomColorHex: "#f06f87"
  },
  {
    id: "plant_hyacinth",
    nameKo: "히아신스",
    rarity: "rare",
    growSeconds: 165,
    rewardCoins: 40,
    stages: 4,
    seedPrice: 25,
    descriptionKo: "촘촘한 꽃송이가 모여 풍성한 실루엣을 만드는 봄꽃.",
    originKo: "동지중해 · 서아시아",
    flowerLanguageKo: "기쁨, 겸손",
    seasonKo: "봄",
    stemColorHex: "#568a52",
    bloomColorHex: "#8f79d8"
  },
  {
    id: "plant_coquelicot",
    nameKo: "양귀비",
    rarity: "common",
    growSeconds: 95,
    rewardCoins: 25,
    stages: 4,
    seedPrice: 15,
    descriptionKo: "가볍게 펼쳐지는 꽃잎이 들판 느낌을 살려주는 꽃.",
    originKo: "유럽",
    flowerLanguageKo: "위로, 평안",
    seasonKo: "봄~초여름",
    stemColorHex: "#5d8948",
    bloomColorHex: "#f1624e"
  },
  {
    id: "plant_freesia",
    nameKo: "프리지아",
    rarity: "common",
    growSeconds: 115,
    rewardCoins: 29,
    stages: 4,
    seedPrice: 18,
    descriptionKo: "은은한 향과 우아한 줄기 라인이 특징인 인기 꽃.",
    originKo: "남아프리카",
    flowerLanguageKo: "천진난만, 새로운 시작",
    seasonKo: "봄",
    stemColorHex: "#568748",
    bloomColorHex: "#f5d96b"
  },
  {
    id: "plant_gerbera",
    nameKo: "거베라",
    rarity: "rare",
    growSeconds: 145,
    rewardCoins: 35,
    stages: 4,
    seedPrice: 23,
    descriptionKo: "원형 꽃잎이 또렷하게 퍼져 화사한 포인트가 된다.",
    originKo: "남아프리카",
    flowerLanguageKo: "희망, 신비",
    seasonKo: "봄~가을",
    stemColorHex: "#548346",
    bloomColorHex: "#ff8b6a"
  },
  {
    id: "plant_lily",
    nameKo: "백합",
    rarity: "rare",
    growSeconds: 150,
    rewardCoins: 37,
    stages: 4,
    seedPrice: 24,
    descriptionKo: "큰 꽃잎과 깨끗한 실루엣이 돋보이는 클래식 꽃.",
    originKo: "북반구 온대",
    flowerLanguageKo: "순결, 고귀함",
    seasonKo: "초여름",
    stemColorHex: "#4d8045",
    bloomColorHex: "#fff5d8"
  },
  {
    id: "plant_lily_of_the_valley",
    nameKo: "은방울꽃",
    rarity: "rare",
    growSeconds: 165,
    rewardCoins: 39,
    stages: 4,
    seedPrice: 25,
    descriptionKo: "작은 종 모양 꽃이 모여 사랑스러운 실루엣을 만든다.",
    originKo: "유럽 · 북아시아",
    flowerLanguageKo: "행복이 다시 찾아옴",
    seasonKo: "봄",
    stemColorHex: "#568a52",
    bloomColorHex: "#f7f7ee"
  },
  {
    id: "plant_lisianthus",
    nameKo: "리시안셔스",
    rarity: "rare",
    growSeconds: 155,
    rewardCoins: 36,
    stages: 4,
    seedPrice: 24,
    descriptionKo: "여러 겹의 부드러운 꽃잎이 고급스러운 분위기를 낸다.",
    originKo: "북아메리카",
    flowerLanguageKo: "변치 않는 사랑",
    seasonKo: "여름",
    stemColorHex: "#4f7f4c",
    bloomColorHex: "#d9a7ef"
  },
  {
    id: "plant_myosotis",
    nameKo: "물망초",
    rarity: "common",
    growSeconds: 105,
    rewardCoins: 27,
    stages: 4,
    seedPrice: 17,
    descriptionKo: "작은 꽃송이가 모여 하늘빛 군락을 만드는 꽃.",
    originKo: "유럽",
    flowerLanguageKo: "나를 잊지 마세요",
    seasonKo: "봄",
    stemColorHex: "#5c8d55",
    bloomColorHex: "#85b7ff"
  },
  {
    id: "plant_pansy",
    nameKo: "팬지",
    rarity: "common",
    growSeconds: 100,
    rewardCoins: 26,
    stages: 4,
    seedPrice: 16,
    descriptionKo: "얼굴 모양 꽃무늬가 귀여운 저온성 대표 꽃.",
    originKo: "유럽",
    flowerLanguageKo: "사색, 그리움",
    seasonKo: "봄~가을",
    stemColorHex: "#57864c",
    bloomColorHex: "#a78cf0"
  },
  {
    id: "plant_peony_blossom",
    nameKo: "작약",
    rarity: "rare",
    growSeconds: 175,
    rewardCoins: 41,
    stages: 4,
    seedPrice: 27,
    descriptionKo: "풍성하게 겹친 꽃잎이 화려한 존재감을 만든다.",
    originKo: "중국 · 시베리아",
    flowerLanguageKo: "수줍음, 부귀",
    seasonKo: "늦봄",
    stemColorHex: "#4f7e49",
    bloomColorHex: "#f49ab2"
  },
  {
    id: "plant_rocket_larkspur",
    nameKo: "델피늄",
    rarity: "epic",
    growSeconds: 185,
    rewardCoins: 46,
    stages: 4,
    seedPrice: 30,
    descriptionKo: "위로 길게 솟는 꽃대가 입체적인 실루엣을 만든다.",
    originKo: "유럽 · 서아시아",
    flowerLanguageKo: "자유, 활기",
    seasonKo: "초여름",
    stemColorHex: "#4d7f4f",
    bloomColorHex: "#6b84e8"
  },
  {
    id: "plant_sunflower",
    nameKo: "해바라기",
    rarity: "epic",
    growSeconds: 200,
    rewardCoins: 50,
    stages: 4,
    seedPrice: 32,
    descriptionKo: "큰 꽃판이 시원하게 펼쳐져 강한 여름 정원 포인트를 준다.",
    originKo: "북아메리카",
    flowerLanguageKo: "동경, 긍정",
    seasonKo: "여름",
    stemColorHex: "#4d8443",
    bloomColorHex: "#f5c746"
  },
  {
    id: "plant_delphinium",
    nameKo: "델피늄",
    rarity: "rare",
    growSeconds: 195,
    rewardCoins: 48,
    stages: 4,
    seedPrice: 31,
    descriptionKo: "길게 솟는 꽃대에 층층이 피는 꽃이 우아한 포인트를 만든다.",
    originKo: "유럽 · 아시아",
    flowerLanguageKo: "자유, 고결",
    seasonKo: "초여름~여름",
    stemColorHex: "#4a7f52",
    bloomColorHex: "#6f8be6"
  },
  {
    id: "plant_lilac",
    nameKo: "라일락",
    rarity: "rare",
    growSeconds: 185,
    rewardCoins: 45,
    stages: 4,
    seedPrice: 29,
    descriptionKo: "풍성한 꽃송이와 은은한 분위기가 매력적인 봄 대표 관목 꽃.",
    originKo: "동유럽 · 발칸",
    flowerLanguageKo: "첫사랑, 추억",
    seasonKo: "봄",
    stemColorHex: "#4d7f4a",
    bloomColorHex: "#b28adf"
  },
  {
    id: "plant_chrysanthemum",
    nameKo: "국화",
    rarity: "rare",
    growSeconds: 190,
    rewardCoins: 44,
    stages: 4,
    seedPrice: 30,
    descriptionKo: "촘촘한 꽃잎 층이 풍성하게 퍼져 가을 정원을 채워주는 꽃.",
    originKo: "동아시아",
    flowerLanguageKo: "성실, 진실",
    seasonKo: "가을",
    stemColorHex: "#5a8747",
    bloomColorHex: "#f2cf6d"
  },
  {
    id: "plant_mugunghwa",
    nameKo: "무궁화",
    rarity: "epic",
    growSeconds: 225,
    rewardCoins: 56,
    stages: 4,
    seedPrice: 38,
    descriptionKo: "대한민국을 상징하는 꽃으로, 여름 햇살 아래 오래 피어나는 꽃.",
    originKo: "동아시아",
    flowerLanguageKo: "끈기, 영원",
    seasonKo: "여름",
    stemColorHex: "#4d7d49",
    bloomColorHex: "#f08eb7"
  },
  {
    id: "plant_monstera",
    nameKo: "몬스테라",
    rarity: "common",
    growSeconds: 180,
    rewardCoins: 38,
    stages: 4,
    seedPrice: 25,
    descriptionKo: "깊게 갈라진 잎이 시원한 존재감을 주는 관엽식물.",
    originKo: "중앙아메리카",
    flowerLanguageKo: "기쁜 소식",
    seasonKo: "사계절",
    stemColorHex: "#3f7f4a",
    bloomColorHex: "#75b56f"
  },
  {
    id: "plant_rubber_tree",
    nameKo: "인도고무나무",
    rarity: "common",
    growSeconds: 210,
    rewardCoins: 44,
    stages: 4,
    seedPrice: 30,
    descriptionKo: "짙은 광택 잎이 매력적인 실내 대표 나무형 식물.",
    originKo: "인도 · 동남아시아",
    flowerLanguageKo: "변함없는 사랑",
    seasonKo: "사계절",
    stemColorHex: "#3a7342",
    bloomColorHex: "#6daa63"
  },
  {
    id: "plant_scindapsus",
    nameKo: "스킨답서스",
    rarity: "rare",
    growSeconds: 240,
    rewardCoins: 52,
    stages: 4,
    seedPrice: 36,
    descriptionKo: "길게 늘어지는 덩굴 형태가 공간을 부드럽게 채운다.",
    originKo: "솔로몬 제도",
    flowerLanguageKo: "우아한 성장",
    seasonKo: "사계절",
    stemColorHex: "#467a3f",
    bloomColorHex: "#7fb870"
  },
  {
    id: "plant_alocasia",
    nameKo: "알로카시아",
    rarity: "rare",
    growSeconds: 220,
    rewardCoins: 47,
    stages: 4,
    seedPrice: 33,
    descriptionKo: "화살촉 잎맥이 선명해 존재감이 강한 관엽식물.",
    originKo: "동남아시아",
    flowerLanguageKo: "우아함, 품격",
    seasonKo: "사계절",
    stemColorHex: "#3f7d45",
    bloomColorHex: "#7cb871"
  },
  {
    id: "plant_anthurium",
    nameKo: "안스리움",
    rarity: "rare",
    growSeconds: 230,
    rewardCoins: 50,
    stages: 4,
    seedPrice: 35,
    descriptionKo: "광택 있는 잎과 이국적인 형태가 돋보이는 실내 식물.",
    originKo: "중남미",
    flowerLanguageKo: "환대, 따뜻함",
    seasonKo: "사계절",
    stemColorHex: "#3f7742",
    bloomColorHex: "#79ad65"
  },
  {
    id: "plant_boston_fern",
    nameKo: "보스턴고사리",
    rarity: "common",
    growSeconds: 170,
    rewardCoins: 36,
    stages: 4,
    seedPrice: 24,
    descriptionKo: "풍성하게 퍼지는 잎으로 공간을 부드럽게 채워주는 고사리.",
    originKo: "열대 아메리카",
    flowerLanguageKo: "편안함, 안정",
    seasonKo: "사계절",
    stemColorHex: "#4a8447",
    bloomColorHex: "#88bf72"
  },
  {
    id: "plant_calathea_orbifolia",
    nameKo: "칼라데아 오르비폴리아",
    rarity: "rare",
    growSeconds: 240,
    rewardCoins: 52,
    stages: 4,
    seedPrice: 36,
    descriptionKo: "넓은 줄무늬 잎이 세련된 분위기를 만드는 관엽식물.",
    originKo: "볼리비아",
    flowerLanguageKo: "정돈, 균형",
    seasonKo: "사계절",
    stemColorHex: "#457a45",
    bloomColorHex: "#7bb66a"
  },
  {
    id: "plant_coffea",
    nameKo: "커피나무",
    rarity: "common",
    growSeconds: 190,
    rewardCoins: 40,
    stages: 4,
    seedPrice: 28,
    descriptionKo: "짙은 녹색 잎이 촘촘해 실내 포인트로 좋은 나무형 식물.",
    originKo: "에티오피아",
    flowerLanguageKo: "여유, 성실",
    seasonKo: "사계절",
    stemColorHex: "#3d6f40",
    bloomColorHex: "#74a65e"
  },
  {
    id: "plant_eucalyptus",
    nameKo: "유칼립투스",
    rarity: "rare",
    growSeconds: 210,
    rewardCoins: 45,
    stages: 4,
    seedPrice: 31,
    descriptionKo: "은은한 색감의 잎이 깔끔한 인테리어 무드를 만든다.",
    originKo: "호주",
    flowerLanguageKo: "치유, 정화",
    seasonKo: "사계절",
    stemColorHex: "#4b7d55",
    bloomColorHex: "#8abf86"
  },
  {
    id: "plant_giant_white_bird_of_paradise",
    nameKo: "여인초",
    rarity: "rare",
    growSeconds: 260,
    rewardCoins: 56,
    stages: 4,
    seedPrice: 39,
    descriptionKo: "큰 잎이 시원하게 뻗어 공간 스케일을 키워주는 식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "자유, 비상",
    seasonKo: "사계절",
    stemColorHex: "#3f7246",
    bloomColorHex: "#74aa6e"
  },
  {
    id: "plant_ivy",
    nameKo: "아이비",
    rarity: "common",
    growSeconds: 160,
    rewardCoins: 34,
    stages: 4,
    seedPrice: 22,
    descriptionKo: "덩굴이 자연스럽게 퍼져 벽면과 선반 연출에 잘 어울린다.",
    originKo: "유럽 · 서아시아",
    flowerLanguageKo: "영원, 우정",
    seasonKo: "사계절",
    stemColorHex: "#3f7d41",
    bloomColorHex: "#78b567"
  },
  {
    id: "plant_money_tree",
    nameKo: "금전수",
    rarity: "common",
    growSeconds: 205,
    rewardCoins: 43,
    stages: 4,
    seedPrice: 30,
    descriptionKo: "두툼한 잎과 단정한 수형이 매력적인 실내 인기 수종.",
    originKo: "중남미",
    flowerLanguageKo: "행운, 번영",
    seasonKo: "사계절",
    stemColorHex: "#416f3f",
    bloomColorHex: "#73a95f"
  },
  {
    id: "plant_philodendron_gloriosum",
    nameKo: "필로덴드론 글로리오섬",
    rarity: "epic",
    growSeconds: 270,
    rewardCoins: 60,
    stages: 4,
    seedPrice: 42,
    descriptionKo: "벨벳 질감의 잎맥이 또렷해 고급스러운 분위기를 연출한다.",
    originKo: "콜롬비아",
    flowerLanguageKo: "품위, 깊이",
    seasonKo: "사계절",
    stemColorHex: "#325f38",
    bloomColorHex: "#679f5d"
  },
  {
    id: "plant_spider_plant",
    nameKo: "나비란",
    rarity: "common",
    growSeconds: 150,
    rewardCoins: 32,
    stages: 4,
    seedPrice: 20,
    descriptionKo: "가늘게 늘어지는 줄무늬 잎이 가볍고 산뜻한 인상을 준다.",
    originKo: "남아프리카",
    flowerLanguageKo: "희망, 활력",
    seasonKo: "사계절",
    stemColorHex: "#4d8447",
    bloomColorHex: "#92c97a"
  },
  {
    id: "plant_staghorn_fern",
    nameKo: "박쥐란",
    rarity: "rare",
    growSeconds: 225,
    rewardCoins: 48,
    stages: 4,
    seedPrice: 34,
    descriptionKo: "사슴뿔 모양 잎이 독특한 실루엣을 만드는 고사리류.",
    originKo: "동남아시아 · 오세아니아",
    flowerLanguageKo: "개성, 강인함",
    seasonKo: "사계절",
    stemColorHex: "#4b7c4a",
    bloomColorHex: "#86b872"
  },
  {
    id: "plant_strelitzia_reginae",
    nameKo: "극락조화",
    rarity: "rare",
    growSeconds: 250,
    rewardCoins: 54,
    stages: 4,
    seedPrice: 37,
    descriptionKo: "탄탄한 잎과 이국적인 분위기로 존재감이 큰 관엽식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "자신감, 당당함",
    seasonKo: "사계절",
    stemColorHex: "#3e7543",
    bloomColorHex: "#74ae68"
  },
  {
    id: "plant_syngonium_podophyllum",
    nameKo: "싱고니움",
    rarity: "common",
    growSeconds: 175,
    rewardCoins: 37,
    stages: 4,
    seedPrice: 25,
    descriptionKo: "화살 모양 잎이 자라며 형태가 변하는 매력적인 덩굴 식물.",
    originKo: "중남미",
    flowerLanguageKo: "성장, 변화",
    seasonKo: "사계절",
    stemColorHex: "#467d45",
    bloomColorHex: "#84bc73"
  },
  {
    id: "plant_yellow_palm",
    nameKo: "아레카야자",
    rarity: "common",
    growSeconds: 185,
    rewardCoins: 39,
    stages: 4,
    seedPrice: 27,
    descriptionKo: "가느다란 야자 잎이 퍼져 밝고 휴양지 같은 분위기를 준다.",
    originKo: "마다가스카르",
    flowerLanguageKo: "평온, 환영",
    seasonKo: "사계절",
    stemColorHex: "#5f8241",
    bloomColorHex: "#a3c86c"
  },
  {
    id: "plant_cotyledon_orbiculata",
    nameKo: "방울복랑",
    rarity: "rare",
    growSeconds: 235,
    rewardCoins: 51,
    stages: 4,
    seedPrice: 35,
    descriptionKo: "은은한 가루빛 잎과 도톰한 형태가 매력적인 다육식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "절제, 단단함",
    seasonKo: "사계절",
    stemColorHex: "#5d8248",
    bloomColorHex: "#b9d48a"
  },
  {
    id: "plant_echeveria",
    nameKo: "에케베리아",
    rarity: "common",
    growSeconds: 175,
    rewardCoins: 38,
    stages: 4,
    seedPrice: 26,
    descriptionKo: "장미처럼 겹겹이 모인 잎이 균형감 있는 실루엣을 만든다.",
    originKo: "멕시코",
    flowerLanguageKo: "아름다움, 조화",
    seasonKo: "사계절",
    stemColorHex: "#668a54",
    bloomColorHex: "#c4dc95"
  },
  {
    id: "plant_lithops",
    nameKo: "리톱스",
    rarity: "epic",
    growSeconds: 290,
    rewardCoins: 66,
    stages: 4,
    seedPrice: 46,
    descriptionKo: "자갈을 닮은 독특한 형태로 소장 가치가 높은 희귀 다육식물.",
    originKo: "남아프리카 사막지대",
    flowerLanguageKo: "인내, 생존",
    seasonKo: "사계절",
    stemColorHex: "#6c7b58",
    bloomColorHex: "#d6db9a"
  },
  {
    id: "plant_sedum_burrito",
    nameKo: "청옥",
    rarity: "common",
    growSeconds: 180,
    rewardCoins: 39,
    stages: 4,
    seedPrice: 27,
    descriptionKo: "알알이 늘어지는 잎이 귀여운 분위기를 만들어주는 세덤.",
    originKo: "멕시코",
    flowerLanguageKo: "여유, 편안함",
    seasonKo: "사계절",
    stemColorHex: "#5f874f",
    bloomColorHex: "#b7d58c"
  },
  {
    id: "plant_sedum_clavatum",
    nameKo: "라울",
    rarity: "rare",
    growSeconds: 225,
    rewardCoins: 49,
    stages: 4,
    seedPrice: 33,
    descriptionKo: "통통한 잎 군집이 퍼지며 차분한 색감을 보여주는 세덤.",
    originKo: "멕시코",
    flowerLanguageKo: "온화함, 안정",
    seasonKo: "사계절",
    stemColorHex: "#648751",
    bloomColorHex: "#bfdc93"
  },
  {
    id: "plant_sedum_species",
    nameKo: "희성",
    rarity: "common",
    growSeconds: 170,
    rewardCoins: 36,
    stages: 4,
    seedPrice: 24,
    descriptionKo: "관리가 쉬워 초보에게도 인기 있는 대표 다육 라인.",
    originKo: "북반구 온대",
    flowerLanguageKo: "강인함, 실용",
    seasonKo: "사계절",
    stemColorHex: "#5e8751",
    bloomColorHex: "#b5d089"
  },
  {
    id: "plant_kalanchoe_thyrsiflora",
    nameKo: "당인",
    rarity: "rare",
    growSeconds: 240,
    rewardCoins: 53,
    stages: 4,
    seedPrice: 37,
    descriptionKo: "겹겹이 쌓인 잎과 붉은 가장자리 색감이 인상적인 다육식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "생동감, 개성",
    seasonKo: "사계절",
    stemColorHex: "#6a8447",
    bloomColorHex: "#d0c884"
  },
  {
    id: "plant_kalanchoe_tomentosa",
    nameKo: "월토이",
    rarity: "rare",
    growSeconds: 230,
    rewardCoins: 50,
    stages: 4,
    seedPrice: 34,
    descriptionKo: "보송한 잎결과 갈색 테두리가 특징인 아기자기한 다육식물.",
    originKo: "마다가스카르",
    flowerLanguageKo: "포근함, 애정",
    seasonKo: "사계절",
    stemColorHex: "#6c8352",
    bloomColorHex: "#cabf8a"
  },
  {
    id: "plant_stuckyi",
    nameKo: "스투키",
    rarity: "common",
    growSeconds: 200,
    rewardCoins: 42,
    stages: 4,
    seedPrice: 28,
    descriptionKo: "곧게 뻗는 잎이 깔끔한 인상을 주는 다육식물.",
    originKo: "아프리카",
    flowerLanguageKo: "강인함",
    seasonKo: "사계절",
    stemColorHex: "#4b8648",
    bloomColorHex: "#92c17a"
  },
  {
    id: "plant_aloe",
    nameKo: "알로에",
    rarity: "rare",
    growSeconds: 230,
    rewardCoins: 50,
    stages: 4,
    seedPrice: 34,
    descriptionKo: "두툼한 잎과 톱니 가장자리가 특징인 대표 다육식물.",
    originKo: "아라비아반도 · 아프리카",
    flowerLanguageKo: "치유, 건강",
    seasonKo: "사계절",
    stemColorHex: "#4f8b4d",
    bloomColorHex: "#8fc66f"
  },
  {
    id: "plant_aloe_mitriformis",
    nameKo: "불야성",
    rarity: "rare",
    growSeconds: 236,
    rewardCoins: 52,
    stages: 4,
    seedPrice: 36,
    descriptionKo: "겹겹이 포개진 잎 배열이 독특한 알로에 계열 다육식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "치유, 강인함",
    seasonKo: "사계절",
    stemColorHex: "#53884f",
    bloomColorHex: "#95c975"
  },
  {
    id: "plant_roadkill_cactus",
    nameKo: "만세선인장",
    rarity: "epic",
    growSeconds: 280,
    rewardCoins: 64,
    stages: 4,
    seedPrice: 44,
    descriptionKo: "강렬한 개성으로 포인트가 되는 희귀 다육 라인.",
    originKo: "멕시코 · 중남미",
    flowerLanguageKo: "생명력, 개척",
    seasonKo: "여름~가을",
    stemColorHex: "#557e3f",
    bloomColorHex: "#c7d57a"
  },
  {
    id: "plant_astrophytum",
    nameKo: "우주목",
    rarity: "rare",
    growSeconds: 245,
    rewardCoins: 53,
    stages: 4,
    seedPrice: 37,
    descriptionKo: "별 모양 능선이 돋보이는 구형 선인장 계열 다육식물.",
    originKo: "멕시코 북부",
    flowerLanguageKo: "개성, 인내",
    seasonKo: "사계절",
    stemColorHex: "#5f7d45",
    bloomColorHex: "#d6cd88"
  },
  {
    id: "plant_black_prince",
    nameKo: "흑법사",
    rarity: "common",
    growSeconds: 190,
    rewardCoins: 41,
    stages: 4,
    seedPrice: 28,
    descriptionKo: "짙은 자주빛 잎 로제트가 매력적인 에케베리아 계열 다육식물.",
    originKo: "원예 교배종",
    flowerLanguageKo: "품격, 매혹",
    seasonKo: "사계절",
    stemColorHex: "#5b6a49",
    bloomColorHex: "#b7b487"
  },
  {
    id: "plant_conophytum_bilobum",
    nameKo: "축전",
    rarity: "rare",
    growSeconds: 238,
    rewardCoins: 52,
    stages: 4,
    seedPrice: 36,
    descriptionKo: "쌍잎이 맞붙은 작은 몸체가 군락을 이루는 메셈계 다육식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "절제, 집중",
    seasonKo: "사계절",
    stemColorHex: "#607b4e",
    bloomColorHex: "#d0c996"
  },
  {
    id: "plant_flame",
    nameKo: "화제",
    rarity: "common",
    growSeconds: 182,
    rewardCoins: 39,
    stages: 4,
    seedPrice: 27,
    descriptionKo: "불꽃처럼 올라오는 잎 색감이 포인트인 다육식물.",
    originKo: "원예 교배종",
    flowerLanguageKo: "열정, 활력",
    seasonKo: "사계절",
    stemColorHex: "#6a8447",
    bloomColorHex: "#d6b37a"
  },
  {
    id: "plant_haworthia",
    nameKo: "십이지권",
    rarity: "common",
    growSeconds: 188,
    rewardCoins: 40,
    stages: 4,
    seedPrice: 27,
    descriptionKo: "투명한 잎맥과 단단한 로제트 형태가 매력적인 소형 다육식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "견고함, 평온",
    seasonKo: "사계절",
    stemColorHex: "#4f7c49",
    bloomColorHex: "#b9d08a"
  },
  {
    id: "plant_splitrock",
    nameKo: "자제옥",
    rarity: "epic",
    growSeconds: 305,
    rewardCoins: 68,
    stages: 4,
    seedPrice: 47,
    descriptionKo: "갈라진 바위 형태를 닮아 존재감이 강한 희귀 다육식물.",
    originKo: "남아프리카 건조지대",
    flowerLanguageKo: "생존, 단단함",
    seasonKo: "사계절",
    stemColorHex: "#6e6f58",
    bloomColorHex: "#d9c89a"
  },
  {
    id: "plant_string_of_pearls",
    nameKo: "콩란",
    rarity: "rare",
    growSeconds: 232,
    rewardCoins: 50,
    stages: 4,
    seedPrice: 35,
    descriptionKo: "구슬 같은 잎이 길게 늘어지는 행잉형 다육식물.",
    originKo: "남아프리카",
    flowerLanguageKo: "연결, 조화",
    seasonKo: "사계절",
    stemColorHex: "#4f8649",
    bloomColorHex: "#b8d48c"
  }
];

export const PLANT_BY_ID: Record<string, PlantSpeciesDef> = Object.fromEntries(
  PLANT_SPECIES_DEFS.map((species) => [species.id, species])
);
